version: '3.3'
services:
    #PHP Service
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: php_service
        container_name: app
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./conf/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - app-network
    #Nginx Service
    webserver:
        image: nginx:alpine
        container_name: webserver
        restart: unless-stopped
        tty: true
        ports:
            - '88:80'
            - '443:443'
        volumes:
            - ./:/var/www
            - ./conf/nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - app-network
    #MySQL Service
    db:
        image: mysql:5.7
        container_name: db
        restart: unless-stopped
        tty: true
        ports:
            - '1306:3306'
        environment:
            MYSQL_DATABASE: smarttrackerdb
            MYSQL_ROOT_PASSWORD: chinedu
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - lbdata:/var/lib/mysql/
        networks:
            - app-network
#Docker Networks
networks:
    app-network:
        driver: bridge
#Volumes
volumes:
    lbdata:
        driver: local
